version: '3'
services:
  api:
    build: .
    ports:
      - "6000:6880"
    volumes:
      - /root/NYOTAPAY/assets:/app/public
    environment:
      NODE_ENV: production
    env_file:
      - .env
    command: ["sh", "-c", "npx sequelize-cli db:migrate --env production && pm2 start app.js --name nyotapay"]